services:

  hz:
    image: hazelcast/hazelcast-enterprise:5.5.0-SNAPSHOT
    environment:
      HZ_LICENSEKEY: ${HZ_LICENSEKEY}
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml -Xmx5g  -XX:+UseZGC -XX:ZCollectionInterval=1
    volumes:
      - ".:/project"
    networks:
      - hznet
  mc:
    image: hazelcast/management-center:5.5-SNAPSHOT
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
    ports:
      - "8080:8080"
    networks:
      - hznet


  submit-image-loader-airplanes:
    image: hazelcast/hazelcast-enterprise:5.5.0-SNAPSHOT
    volumes:
      - ".:/project"
    command: >
      hz-cli submit 
          -v 
          -c=hazelcast.platform.labs.image.similarity.ImageEncodePipeline 
          -t=dev@hz   
          /project/image-encode-pipeline/target/image-encode-pipeline-1.0-SNAPSHOT.jar 
          /project/images/caltech-101/101_ObjectCategories/airplanes
    networks:
      - hznet
    profiles:
      - disabled

  submit-image-loader-butterfly:
    image: hazelcast/hazelcast-enterprise:5.5.0-SNAPSHOT
    volumes:
      - ".:/project"
    command: >
      hz-cli submit 
          -v 
          -c=hazelcast.platform.labs.image.similarity.ImageEncodePipeline 
          -t=dev@hz   
          /project/image-encode-pipeline/target/image-encode-pipeline-1.0-SNAPSHOT.jar 
          /project/images/caltech-101/101_ObjectCategories/butterfly
    networks:
      - hznet
    profiles:
      - disabled

networks:
  hznet: 
  
